config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'admin/index'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'
  resources :products do
    get :who_bought, on: :member
  end

  resources :products

  root 'store#index', as: 'store'
  match '/home', to: 'store#index', via: 'get'
  match '/carts', to: 'carts#show', via: 'get'
  match '/products', to: 'products#show', via: 'get'

end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <!-- START_HIGHLIGHT -->
  <title>Pragprog Books Online Store</title>
  <!-- END_HIGHLIGHT -->
  <!-- <label id="code.slt"/> --><%= stylesheet_link_tag "application", media: "all",
                                                         "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %><!-- <label id="code.jlt"/> -->
  <%= csrf_meta_tags %><!-- <label id="code.csrf"/> -->
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<!-- START_HIGHLIGHT -->
<div id="banner">
  <%= image_tag("logo.png") %>
  <%= @page_title || "Pragmatic Bookshelf" %><!-- <label id="code.depot.e.title"/> -->
</div>
<nav>
  <div id="columns">
    <div id="side">
      <% if @cart %>
      <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
      <% end %>
      <% end %>
      <ul class = "navbar">
        <li><%= link_to "Home", store_path %></li>
        <li><a href="http://www..../faq">Questions</a></li>
        <li><a href="http://www..../news">News</a></li>
        <li><a href="http://www..../contact">Contact</a></li>
        <!--<li><%= link_to "Cart", carts_path %></li>-->
        <li><%= link_to "Products", products_path %></li>
      </ul>
      <div id="clock"><%= Time.now %></div>
      <p id = 'quote'>
        <strong><em>Don't disturb me here.</em></strong>
        <p id = 'wangyeye'>--- Grandpa Wang</p>
      </p>

      <% if session[:user_id] %>
          <hr/>
          <h5>Login as <%= (User.find_by_id(session[:user_id])).name%></h5>
          <ul>
            <li><%= link_to 'Orders',   orders_path   %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users',    users_path    %></li>
          </ul>
          <%= button_to 'Logout', logout_path, method: :delete, class:"btn btn-warning"   %>
      <% end %>

    </div>

    <div id="main">
      <!-- END_HIGHLIGHT -->
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
      <!-- START_HIGHLIGHT -->
    </div>
  </div>
</nav>
<!-- END_HIGHLIGHT -->
</body>
</html>